# Generated by Django 4.2.3 on 2023-07-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
